import { StyleSheet } from 'react-native';

export const stockStyles = StyleSheet.create({
  stockContainer: {
    flex: 1,
    backgroundColor: '#fff',
    paddingBottom: 16,
  },
  stockHeader: {
    paddingTop: 50,
    paddingBottom: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  stockHeaderContent: {
    marginTop: 16,
  },
  stockSymbol: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#111',
    marginBottom: 4,
  },
  stockName: {
    fontSize: 16,
    color: '#666',
    marginBottom: 2,
  },
  stockExchange: {
    fontSize: 14,
    color: '#999',
  },
  backButton: {
    padding: 8,
    marginLeft: -8,
  },
  priceContainer: {
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  currentPrice: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#111',
    marginBottom: 4,
  },
  priceChangeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  priceChange: {
    fontSize: 16,
    marginLeft: 4,
    fontWeight: '600',
  },
  timeFrameSelector: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    gap: 8,
  },
  timeFrameButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  timeFrameButtonActive: {
    backgroundColor: '#3b82f6',
    borderColor: '#3b82f6',
  },
  timeFrameText: {
    color: '#666',
    fontSize: 13,
    fontWeight: '600',
  },
  timeFrameTextActive: {
    color: '#fff',
  },
  chartContainer: {
    height: 250,
    backgroundColor: '#fff',
    padding: 16,
    marginVertical: 16,
  },
  chartPlaceholder: {
    flex: 1,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  chartPlaceholderText: {
    color: '#64748b',
    fontSize: 16,
    fontWeight: '600',
  },
  statsContainer: {
    padding: 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  statItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 4,
  },
  statLabel: {
    color: '#666',
    fontSize: 14,
  },
  statValue: {
    color: '#111',
    fontSize: 14,
    fontWeight: '600',
  },
  actionButtons: {
    flexDirection: 'row',
    padding: 16,
    paddingBottom: 32,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    gap: 12,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  buyButton: {
    backgroundColor: '#4CAF50',
    marginRight: 8,
    shadowColor: '#4CAF50',
  },
  sellButton: {
    backgroundColor: '#F44336',
    marginLeft: 8,
    shadowColor: '#F44336',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});